name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11 ]
        java-distribution: [ 'adopt', 'zulu' ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}

      - uses: coursier/cache-action@v6

      - name: Run
        run: ./sbt jmh:run
